name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: build
    permissions:
      contents: write
    concurrency: deploy-docs-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: install dependencies
        run: yarn install

      - name: build docs
        run: yarn build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build